name: twitter_client
description: A twitter API wrapper for Dart.
version: 1.0.2
publish_to: none
homepage:

environment:
  sdk: '>=3.0.0'

dependencies:
  crypto: ^3.0.6
  http: ^1.2.2

dev_dependencies: 
  test: ^1.19.3
