name: twitter_client
description: A twitter API wrapper for Dart.
version: 1.0.1
publish_to: none
homepage:

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  http: ^0.13.4

dev_dependencies: 
  test: ^1.19.3
